/* DELETE 'easyBookingdb' database*/
DROP SCHEMA IF EXISTS easyBookingdb;
/* DELETE USER 'sd' AT LOCAL SERVER*/
DROP USER IF EXISTS 'sd'@'%';

/* CREATE ''easyBookingdb' DATABASE */
CREATE SCHEMA easyBookingdb;
/* CREATE THE USER 'sd' AT LOCAL SERVER WITH PASSWORD 'sd' */
CREATE USER IF NOT EXISTS 'sd'@'%' IDENTIFIED BY 'sd';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'sd' AT LOCAL SERVER*/
GRANT ALL ON easyBookingdb.* TO 'sd'@'%';
